#!/usr/bin/env bash
# script that transfers a file from our client to a server

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

pathToFile=$1
IP=$2
username=$3
pathToSSH=$4

export SSHPASS="-o StrictHostKeyChecking=no"
scp -i "$pathToSSH" "$pathToFile" "$username@$IP":~/
unset SSHPASS
