#!/usr/bin/env bash
# script that transfers a file from our client to a server
n=$#
pathToFile=$1
IP=$2
username=$3
pathToSSH=$4

if [ $n -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp "$pathToFile" "$username@$IP":~/ -i "$pathToSSH"
fi
