#!/usr/bin/env bash
# Install nginx on your web-01

sudo apt -y update;
sudo apt -y install nginx;
sudo ufw allow 'Nginx HTTP';
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html';
sudo service nginx start;
