#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html';
sudo sed -i '/listen 80 default_server/a \        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
