#!/usr/bin/env bash
# change the port to 80 instead of 8080
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
